describe("AllPages", function () {
  it("Pages", function () {
    cy.viewport(1920, 1080);
    cy.visit("https://bestcomp.net/az");
    cy.location("protocol").should("eq", "https:");
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/3/heller-ve-xidmetler"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/7/sistem-inteqrasiyasi"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/8/biznes-proseslerinin-avtomatlasdirilmasi"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/9/biznes-davamliliginin-planlanmasi"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/10/sebeke-helleri"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/11/melumat-merkezi"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/12/tehlukesizlik-insfrastrukturu"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/14/enerji-teminati-ve-soyutma-sistemi"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/21/melumat-merkezi-soyutma-sistemi"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/22/kesintisiz-enerji-techizati"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/15/strukturlasmis-kabel-sistemi"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/16/audio-ve-video-helleri"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/23/konfrans-zallari-ve-toplanti-otaqlari"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/36/cagri-merkezi"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/25/vahid-kommunikasiya-helleri"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/17/tetbiq-ve-proqram-teminati"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/18/konsaltinq-ve-autsors-xidmetleri"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/19/247-pesekar-destek-xidmeti"]').click({force:true, multiple: true});
    cy.get('ul[class="sub-menu"]').invoke('show').click({force:true, multiple: true});
    cy.get('a[href="https://bestcomp.net/az/menu/detail/20/resmi-servis-merkezi"]').click({force:true, multiple: true});
  });
});